name: "bump package version"

on: 
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: choice
        description: Is it Major, Minor or a Patch?
        options:
          - major
          - minor
          - patch

jobs:
  bumpVersion:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup git config
      run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
    - name: Bump version
      run: "npm version ${{ github.event.inputs.name }}"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
    # - name: Push commit
    #   run: git push --follow-tags