name: bump package version

on: 
  workflow_dispatch:
    inputs:
      name:
        required: true
        type: choice
        description: Is it Major, Minor or a Patch?
        options:
          - major
          - minor
          - patch

jobs:
  bumpVersion:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Bump version
      run: "npm version ${{ github.event.inputs.name }}"